# Generated by Django 6.0.4 on 2026-06-17 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_number',
            new_name='number',
        ),
    ]
