# Generated by Django 6.0.6 on 2026-06-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='businesses/qrcodes/'),
        ),
    ]
