# Generated by Django 6.0.6 on 2026-06-20 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_phone_number_user_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='phone_number',
            new_name='number',
        ),
    ]
