# Generated by Django 6.0.6 on 2026-06-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_business_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
