# Generated by Django 6.0.6 on 2026-06-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_qr_code_business_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='publicMenuUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
