# Generated by Django 6.0.6 on 2026-06-25 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_business_publicmenuurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='publicMenuUrl',
        ),
    ]
