from django.urls import path

from purchase.presentation.api.views.supplier import (
    SupplierDetailAPIView,
    SupplierListCreateAPIView,
)
from purchase.presentation.api.views.requisition import (
    RequisitionApproveAPIView,
    RequisitionDetailAPIView,
    RequisitionListCreateAPIView,
    RequisitionRejectAPIView,
    RequisitionSubmitAPIView,
)
from purchase.presentation.api.views.purchase_order import (
    PurchaseOrderCancelAPIView,
    PurchaseOrderDetailAPIView,
    PurchaseOrderListCreateAPIView,
    PurchaseOrderSendAPIView,
)
from purchase.presentation.api.views.goods_receipt import (
    GoodsReceiptDetailAPIView,
    GoodsReceiptListCreateAPIView,
)
from purchase.presentation.api.views.purchase_invoice import (
    PurchaseInvoiceApproveAPIView,
    PurchaseInvoiceCancelAPIView,
    PurchaseInvoiceDetailAPIView,
    PurchaseInvoiceListCreateAPIView,
    PurchaseInvoiceMatchAPIView,
    PurchaseInvoicePostAPIView,
)
from purchase.presentation.api.views.supplier_payment import (
    SupplierPaymentDetailAPIView,
    SupplierPaymentListCreateAPIView,
)
from purchase.presentation.api.views.accounts_payable import (
    AccountsPayableDetailAPIView,
    AccountsPayableListAPIView,
    AccountsPayablePaymentEligibilityAPIView,
)
from purchase.presentation.api.views.payment_allocation import (
    PaymentAllocationDetailAPIView,
    PaymentAllocationListCreateAPIView,
)

app_name = "purchase"

urlpatterns = [
    path(
        "payment-allocations/",
        PaymentAllocationListCreateAPIView.as_view(),
        name="payment-allocation-list-create",
    ),
    path(
        "payment-allocations/<int:pk>/",
        PaymentAllocationDetailAPIView.as_view(),
        name="payment-allocation-detail",
    ),
    path(
        "accounts-payables/",
        AccountsPayableListAPIView.as_view(),
        name="accounts-payable-list",
    ),
    path(
        "accounts-payables/<int:pk>/",
        AccountsPayableDetailAPIView.as_view(),
        name="accounts-payable-detail",
    ),
    path(
        "accounts-payables/<int:pk>/payment-eligibility/",
        AccountsPayablePaymentEligibilityAPIView.as_view(),
        name="accounts-payable-payment-eligibility",
    ),
    path(
        "purchase-invoices/",
        PurchaseInvoiceListCreateAPIView.as_view(),
        name="purchase-invoice-list-create",
    ),
    path(
        "purchase-invoices/<int:pk>/",
        PurchaseInvoiceDetailAPIView.as_view(),
        name="purchase-invoice-detail",
    ),
    path(
        "purchase-invoices/<int:pk>/approve/",
        PurchaseInvoiceApproveAPIView.as_view(),
        name="purchase-invoice-approve",
    ),
    path(
        "purchase-invoices/<int:pk>/match/",
        PurchaseInvoiceMatchAPIView.as_view(),
        name="purchase-invoice-match",
    ),
    path(
        "purchase-invoices/<int:pk>/post/",
        PurchaseInvoicePostAPIView.as_view(),
        name="purchase-invoice-post",
    ),
    path(
        "purchase-invoices/<int:pk>/cancel/",
        PurchaseInvoiceCancelAPIView.as_view(),
        name="purchase-invoice-cancel",
    ),
    path(
        "goods-receipts/",
        GoodsReceiptListCreateAPIView.as_view(),
        name="goods-receipt-list-create",
    ),
    path(
        "goods-receipts/<int:pk>/",
        GoodsReceiptDetailAPIView.as_view(),
        name="goods-receipt-detail",
    ),
    path(
        "purchase-orders/",
        PurchaseOrderListCreateAPIView.as_view(),
        name="purchase-order-list-create",
    ),
    path(
        "purchase-orders/<int:pk>/",
        PurchaseOrderDetailAPIView.as_view(),
        name="purchase-order-detail",
    ),
    path(
        "purchase-orders/<int:pk>/send/",
        PurchaseOrderSendAPIView.as_view(),
        name="purchase-order-send",
    ),
    path(
        "purchase-orders/<int:pk>/cancel/",
        PurchaseOrderCancelAPIView.as_view(),
        name="purchase-order-cancel",
    ),
    path(
        "requisitions/",
        RequisitionListCreateAPIView.as_view(),
        name="requisition-list-create",
    ),
    path(
        "requisitions/<int:pk>/",
        RequisitionDetailAPIView.as_view(),
        name="requisition-detail",
    ),
    path(
        "requisitions/<int:pk>/submit/",
        RequisitionSubmitAPIView.as_view(),
        name="requisition-submit",
    ),
    path(
        "requisitions/<int:pk>/approve/",
        RequisitionApproveAPIView.as_view(),
        name="requisition-approve",
    ),
    path(
        "requisitions/<int:pk>/reject/",
        RequisitionRejectAPIView.as_view(),
        name="requisition-reject",
    ),
    path(
        "suppliers/",
        SupplierListCreateAPIView.as_view(),
        name="supplier-list-create",
    ),
    path(
        "suppliers/<int:pk>/",
        SupplierDetailAPIView.as_view(),
        name="supplier-detail",
    ),
    path(
        "supplier-payments/",
        SupplierPaymentListCreateAPIView.as_view(),
        name="supplier-payment-list-create",
    ),
    path(
        "supplier-payments/<int:pk>/",
        SupplierPaymentDetailAPIView.as_view(),
        name="supplier-payment-detail",
    ),
]
