# Generated by Django 6.1 on 2026-09-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_purchaseinvoice_purchaseinvoiceitem_purchaseorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceipt',
            name='received_date',
            field=models.DateTimeField(),
        ),
    ]
